name: "Docker_qinglong"
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker_qinglong
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: k1483162508/qinglong
          dockerFile: qinglong/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: github
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
