name: "Tgcf-docker"
on:
  push:
    branches:
      - main
  workflow_dispatch:
  watch:
        types: [started]
  repository_dispatch:
        types: build_image_Tgcf
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Tgcf-docker
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: k1483162508/telegram
          dockerFile: tgcf/Dockerfile
          platform: linux/amd64,linux/arm64
          tag: tgcf
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
